### ISSUE TITLE
Integrate Kiwirious sensor to control heart rate

### ISSUE THREAD

**Issue by mpnash** [ABI-Web-Apps/medtech-heart-vue#11]

**Comment by LIN810116** [comment]
The code can be found in the original **MedTechHeart** repository in the branch of [kiwrious-integration](https://github.com/ABI-Web-Apps/MedTechHeart/tree/kiwrious-integration)

This version is currently hosted the ABI sitesdev server [here](http://sitesdev.bioeng.auckland.ac.nz/clin864/MedTechHeart/index.html)
